@baseUrl = http://localhost:3000

### Listar libros
GET {{baseUrl}}/api/libros

### Ver un libro
GET {{baseUrl}}/api/libros/1

### Libro inexistente
GET {{baseUrl}}/api/libros/999

### Crear libro
POST {{baseUrl}}/api/libros
Content-Type: application/json

{
  "titulo": "Rayuela",
  "autor": "Julio Cortázar",
  "imagen": "https://covers.openlibrary.org/b/id/8231992-M.jpg",
  "precio": 7000,
  "disponible": true
}

### Editar libro
PUT {{baseUrl}}/api/libros/1
Content-Type: application/json

{
  "titulo": "Cien años de soledad",
  "autor": "Gabriel García Márquez",
  "imagen": "https://covers.openlibrary.org/b/id/8739161-M.jpg",
  "precio": 11000,
  "disponible": true
}

### Borrar libro
DELETE {{baseUrl}}/api/libros/3

### Listar autores
GET {{baseUrl}}/api/autores

### Ver un autor
GET {{baseUrl}}/api/autores/1

### Autor inexistente
GET {{baseUrl}}/api/autores/999

### Crear autor
POST {{baseUrl}}/api/autores
Content-Type: application/json

{
  "nombre": "Julio Cortázar"
}

### Editar autor
PUT {{baseUrl}}/api/autores/1
Content-Type: application/json

{
  "nombre": "Gabriel García Márquez"
}

### Borrar autor
DELETE {{baseUrl}}/api/autores/3